site_name: must-tui
site_description: Documentation for the must-tui project
site_url: https://ivs-kuleuven.github.io/must-tui/
repo_name: IvS-KULeuven/must-tui
repo_url: https://github.com/IvS-KULeuven/must-tui

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google
            members_order: source
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: false
            show_root_heading: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            show_source: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/api.css

nav:
  - Home: index.md
  - User Guide: user.md
  - Using the TUI: usage.md
  - Developer Guide: developer.md
  - Environment: env.md
  - API Reference: api.md
